# Site settings
title: "Benji Mauer"
email: hey@heybenji.co
author: Benji Mauer
description: I do training, support, and user experience design for rad people.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.heybenji.co" # the base hostname & protocol for your site
twitter_username: heybenji
github_username:  heybenji
social_image: /images/social/benji-site-image.jpg

# Defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Permalinks
permalink: /posts/:title/

# Build settings
markdown: kramdown

# Minify CSS
sass:
  style: compressed
